name: Echiquier Villeneuve-Tolosane
markdown: kramdown
highlighter: rouge
prose:
  media: "photos"
  siteurl: "http://echiquier-villeneuve-tolosane.github.io"
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          label: "Layout"
          element: "text"
          value: "default"
      - name: "root"
        field:
          label: "Racine"
          element: "text"
          value: "../../.."
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "Le titre"